# Generated by Django 5.1.4 on 2025-01-16 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_cron', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CronJobLock',
        ),
        migrations.RemoveIndex(
            model_name='cronjoblog',
            name='django_cron_code_89ad04_idx',
        ),
        migrations.RemoveIndex(
            model_name='cronjoblog',
            name='django_cron_code_21f381_idx',
        ),
        migrations.RemoveIndex(
            model_name='cronjoblog',
            name='django_cron_code_966ed3_idx',
        ),
    ]
